# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-and-test-with-verify

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dotnet-build-and-test-with-Verify:

    runs-on: ubuntu-latest

    steps:
    - run: echo "GitHub repository: ${{ github.repository }}"  # Gibt das Repository aus
    - run: echo "Branch name: ${{ github.ref }}"  # Gibt den Branch-Namen aus
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Test with Verify
      run: dotnet test --no-build --verbosity normal
