name: Welcome New Fork

on:
  fork:
    types: [created]
  workflow_dispatch:

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Send Welcome Message
      uses: actions/github-script@v6
      with:
        script: |
          const { data: issue } = await github.rest.issues.create({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            title: "Willkommen zum Projekt!",
            body: `Hallo @${context.actor} 👋,

Danke, dass du dieses Repository geforkt hast! 🚀

Falls du Unterstützung brauchst oder Fragen hast, findest du hier einige hilfreiche Links:

- **Dokumentation:** [Link zur Doku]
- **Beitragsrichtlinien:** [Link zu den Guidelines]
- **Fragen & Hilfe:** [Link zu Diskussionen/Issues]

Wir freuen uns, dass du dabei bist! 😊

Viel Erfolg und happy coding!`
          });
