name: Welcome New Fork

on:
  fork:
    types: [created]
  workflow_dispatch:

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Send Welcome Message
      uses: actions/github-script@v6
      with:
        script: |
          const { data: issue } = await github.rest.issues.create({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            title: "Willkommen zum Projekt!",
            body: `Hallo @${context.actor} Wir freuen uns, dass du dabei bist!`
          });
